# Generated by Django 6.0 on 2025-12-09 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0002_pengaduan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pengaduan',
            options={'ordering': ['-tanggal_lapor'], 'verbose_name_plural': 'Pengaduan'},
        ),
        migrations.AlterModelOptions(
            name='warga',
            options={'ordering': ['nama_lengkap'], 'verbose_name_plural': 'Warga'},
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='pelapor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengaduan', to='warga.warga', verbose_name='Pelapor'),
        ),
    ]
